apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter-service
  template:
    metadata:
      labels:
        app: counter-service
    spec:
      containers:
        - name: counter-service
          image: counter-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: micro-config
          env:
            - name: SERVICE_NAME
              value: counter-service
---
apiVersion: v1
kind: Service
metadata:
  name: counter-service
spec:
  selector:
    app: counter-service
  ports:
    - port: 8000
      targetPort: 8000